spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3333/db_test?useSSL=false&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ydea123
    name: db_test